### ISSUE TITLE
Morea 2.0: GitHub Actions To The Rescue

### ISSUE THREAD

**Issue by philipmjohnson** [morea-framework/core#17]
As I've gotten more facile with GitHub Actions, it's occurred to me that they create a straightforward way to simplify the use of the Morea Framework so significantly that it motivates a new major version number increment to 2.0.

## The problem with Morea 1.0: managing the master and gh-pages directories and branches

Currently, setup of Morea sites is complicated by the fact that each site requires two local subdirectories, a "master" subdirectory (containing the source files and set to the master branch on GitHub) and a "gh-pages" subdirectory (containing the HTML, and set to the gh-pages branch on GitHub).  

Publishing a site requires you to run a script that runs Jekyll, then puts the HTML into the gh-pages directory, then commits both the master branch and the gh-pages branch. 

Here are some of the problems with this approach:  

* You need special, currently unix-only scripts to build and publish a site.  
* You need a run a script (morea-pull) to pull both branches, and you must do that before publishing.  Otherwise you are in danger of getting a large number of conflicts in the gh-pages directory in the case that multiple people are working on the same site.  
* Windows people have a very difficult time with Morea.  Maybe that should be "impossible time".
* Explaining this to new users is complicated.

## The solution: use GitHub actions to build the site

Here's a simple change with profound usability impact:  create a GitHub action that runs Jekyll and commits the HTML to the gh-pages branch each time there is a commit to the master branch. 

This has the following implications:

* You do not need any special scripts for Morea.  Instead, you download the master branch using the Git client of your choice. You run the system with a simple `jekyll serve --baseurl ''`.  You commit (and publish) your changes using the Git client of your choice. 
* You do not need multiple local subdirectories. You just have a directory containing your Morea source code (the master branch). 
* For simple changes, you can go directly to GitHub and use the browser-based editor to modify a source file and commit it. In some cases, a user might be able to manage their Morea site exclusively through the browser-based editor and never have to install anything localy.
* The barrier to entry for Windows people is reduced. 
* Merge errors are much easier to deal with, because they can only occur within the master branch. (GitHub Action execution is atomic and sequential, so gh-pages will never have a merge conflict if it's only written to by the GitHub Action).
* If there is a build failure, you will get an email from GitHub with a link to the Action log, which will indicate what failed. 
* Users who want to push commits to GitHub (as a backup strategy) without triggering a rebuild of the page will need to use a branch-and-merge strategy.  This adds a bit of complication for new users.

## How to implement this change

The implementation should be extremely easy:

* Write the GitHub Action.
* Delete all scripts.
* Update documentation to explain the new workflow.

I am thinking Summer 2021.  Seems awkward to do this during the semester.   This would also be a reasonable time to do some maintenance upgrades (jekyll, bootstrap, etc.)

**Comment by dport96** [comment]
YES! This will be much better. I've already started doing this for some small things for my ITM352 Morea site and tried building the whole site on GitHub but ran into some configuration issues (setting the correct paths in particular) which can easily be dealt with through GitHub Actions. 

Count me in to help with this if you need!
