### ISSUE TITLE
Better management of posts?

### ISSUE THREAD

**Issue by henricasanova** [morea-framework/core#9]
I am not sure whether this is fixable because it may be all about Jekyll, but I often find managing posts (master/src/_posts) a bit painful, especially because it seems filenames have to start with a date(?). I am wondering whether there would be a way to have a single file for instance, with all the posts in it.  I just spend quite a bit of time editing posts manually and do make mistakes.  Of course, some of us could develop an amazing ncurses tool to visualize posts ;)

This is not really a clear "issue" and if it's not even a MOREA issue then feel free to remove this :)

**Comment by philipmjohnson** [comment]
File name format is a Jekyll constraint:

http://jekyllrb.com/docs/posts/

I think if you find this problematic, you could create a single page with your own custom formatting and just avoid the entire Jekyll "post" abstraction.

**Comment by philipmjohnson** [comment]
If there's some kind of template we could build into Morea that solves your problem, I'm open.

**Comment by henricasanova** [comment]
I do find the standard Jekyll thing problematic, and so, yes, I'll likely start creating my own page with formatting.  We'll see where I get, and then perhaps that can then become part of Morea...
